version: "${VERSION}"

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: app
    env_file:
      - ./.env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - psql_bp
      - redis
    restart: always 
    networks:
      - backend

  psql_bp:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DBNAME}
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
    ports:
      - "${DBPORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    ports:
      - "${REDISPORT}:6379"
    networks:
      - backend

volumes:
  psql_volume_bp:

networks:
  backend:
    driver: bridge
